apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-serving-config
  labels:
    app: ml-serving-api
    component: config
data:
  MLP_MLFLOW_TRACKING_URI: "http://mlflow:5000"
  MLP_SERVING_HOST: "0.0.0.0"
  MLP_SERVING_PORT: "8000"
  MLP_SERVING_MODEL_NAME: "ml-deployment-model"
  MLP_SERVING_MODEL_STAGE: "Production"
  MLP_LOGGING_LEVEL: "INFO"
